ShisheVere/Models/Shishe.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ShisheVere.Models
{
    public class Shishe
    {
        private Shishe shishe;

        public Shishe(Shishe shishe)
        {
            this.shishe = shishe;
        }

        public Shishe()
        {
        }

        [Key]
        public int Id_shishe { get; set; }
        
        public string Emertim { get; set; }
        
        public decimal Kapacitet { get; set; }
     
        public decimal Pesha { get; set; }
        
        public decimal Gjatesia { get; set; }
       
        public decimal Diametri { get; set; }

        public decimal Price { get; set; }
        public int Sasia { get; set; }
        public int id_kategori { get; set; }

        public int id_prodhues { get; set; }

        public string status { get; set; }

        public virtual ICollection<Foto> Foto { get; set; }

        public virtual Kategori KATEGORI { get; set; }

        public virtual Prodhues Prodhues { get; set; }
    }


}

ShisheVere/Controllers/ShisheController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShisheVere.DBCONTEXT;
using ShisheVere.Models;
using System.Web.UI.WebControls;
using System.IO;
using ShisheVere.Security;
using ShisheVere.ViewModels;

namespace AppShisheVere.Controllers
{
    public class ShisheController : Controller
    {
        private StoreContext db = new StoreContext();

        [CostumAuthorize(Roles = "admin,user")]
        // GET: Shishe
        public ActionResult Index(string search)
        {
            var shishe = db.Shishe.Include(s => s.KATEGORI).Include(s => s.Prodhues);

            if (!string.IsNullOrEmpty(search))
            {
                shishe = shishe.Where(p => p.KATEGORI.Emertim.Equals(search) || p.Emertim.Contains(search) || p.Prodhues.Emertim.Contains(search));
                ViewBag.Search = search;
            }

            IEnumerable<SelectListItem> x = shishe.OrderBy(p => p.Gjatesia).Select(c => new SelectListItem { Value = c.Gjatesia.ToString(), Text = c.Gjatesia.ToString() }).Distinct();
            ViewBag.Gjatesi = x;
            IEnumerable<SelectListItem> y = shishe.OrderBy(p => p.Diametri).Select(c => new SelectListItem { Value = c.Diametri.ToString(), Text = c.Diametri.ToString() }).Distinct();
            ViewBag.Diametri = y;
            if (Session["roli"].ToString() == "admin")
                return View(shishe.ToList());
            else return View("UserIndex", shishe.ToList());
        }


        [CostumAuthorize(Roles = "admin,user")]
        // GET: Shishe/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shishe shishe = db.Shishe.Find(id);
            if (shishe == null)
            {
                return HttpNotFound();
            }
            if (Session["roli"].ToString() == "admin")
                return View(shishe);
            else return View("UserDetails", shishe);
        }

        // GET: Shishe/Create
        [CostumAuthorize(Roles = "admin,prodhues")]
        public ActionResult Create()
        {
            ViewBag.id_kategori = new SelectList(db.Kategori, "Id_kategori", "Emertim");
            ViewBag.id_prodhues = new SelectList(db.Prodhues, "Id_prodhues", "Emertim");
            return View();
        }

        [CostumAuthorize(Roles = "admin,prodhues")]
        // POST: Shishe/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection form, HttpPostedFileBase file)
        {
            Shishe shishe = new Shishe
            {
                Emertim = form["Emertim"].ToString(),
                Kapacitet = Convert.ToDecimal(form["Kapacitet"]),
                Pesha = Convert.ToDecimal(form["Pesha"]),
                Gjatesia = Convert.ToDecimal(form["Gjatesia"]),
                Diametri = Convert.ToDecimal(form["Diametri"]),
                Price = Convert.ToDecimal(form["Price"]),
                id_kategori = Convert.ToInt32(form["id_kategori"]),
                id_prodhues = Convert.ToInt32(form["id_prodhues"]),
                status = "pritje"
            };
            if (ModelState.IsValid)
            {
                db.Shishe.Add(shishe);
                db.SaveChanges();
                if (file != null)
                {
                    Foto foto = new Foto();
                    var allowedExtensions = new[] { ".jpg", ".png", ".jpg", "jpeg" };
                    foto.Status = "aktiv";
                    foto.File = "/Images/" + file.FileName;
                    foto.Id_shishe = shishe.Id_shishe;
                    var fileName = Path.GetFileName(file.FileName); //getting only file name(ex-ganesh.jpg)  
                    var ext = Path.GetExtension(file.FileName); //getting the extension(ex-.jpg)  
                    if (allowedExtensions.Contains(ext)) //check what type of extension  
                    {
                        string name = Path.GetFileNameWithoutExtension(fileName); //getting file name without extension  
                        string myfile = name + ext; //appending the name with id  
                                                    // store the file inside ~/project folder(Img)  
                        var path = Path.Combine(Server.MapPath("/Images/"), myfile);
                        foto.File = "/Images/" + file.FileName;
                        db.Foto.Add(foto);
                        db.SaveChanges();
                        file.SaveAs(path);
                    }
                    else
                    {
                        ViewBag.message = "Please choose only Image file";
                    }
                }
                return RedirectToAction("Index");
            }
            ViewBag.id_kategori = new SelectList(db.Kategori, "Id_kategori", "Emertim", shishe.id_kategori);
            ViewBag.id_prodhues = new SelectList(db.Prodhues, "Id_prodhues", "Emertim", shishe.id_prodhues);
            return View(shishe);
        }
        [CostumAuthorize(Roles = "admin")]
        // GET: Shishe/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Shishe shishe = db.Shishe.Find(id);
            if (shishe == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_kategori = new SelectList(db.Kategori, "Id_kategori", "Emertim", shishe.id_kategori);
            ViewBag.id_prodhues = new SelectList(db.Prodhues, "Id_prodhues", "Emertim", shishe.id_prodhues);
            return View(shishe);
        }
        [CostumAuthorize(Roles = "admin")]
        // POST: Shishe/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Shishe shishe, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(shishe).State = EntityState.Modified;
                db.SaveChanges();
            }
            if (file != null)
            {
                var f = db.Foto.Where(p => p.Id_shishe == shishe.Id_shishe).FirstOrDefault();
                Foto foto = new Foto();
                var allowedExtensions = new[] { ".jpg", ".png", ".jpg", "jpeg" };
                foto.Status = "aktiv";
                foto.File = "/Images/" + file.FileName;
                foto.Id_shishe = shishe.Id_shishe;
                var fileName = Path.GetFileName(file.FileName); //getting only file name(ex-ganesh.jpg)  
                var ext = Path.GetExtension(file.FileName); //getting the extension(ex-.jpg)  
                if (allowedExtensions.Contains(ext)) //check what type of extension  
                {
                    string name = Path.GetFileNameWithoutExtension(fileName); //getting file name without extension  
                    string myfile = name + ext; //appending the name with id  
                                                // store the file inside ~/project folder(Img)  
                    var path = Path.Combine(Server.MapPath("/Images/"), myfile);
                    foto.File = "/Images/" + file.FileName;
                    f.Id_shishe = foto.Id_shishe;
                    f.File = foto.File;
                    f.Status = "aktiv";
                    db.SaveChanges();
                    file.SaveAs(path);
                    TempData["edit"] = "Modifikimi u krye me sukses !";
                }
                else
                {
                    ViewBag.message = "Please choose only Image file";
                }
            }
            ViewBag.id_kategori = new SelectList(db.Kategori, "Id_kategori", "Emertim", shishe.id_kategori);
            ViewBag.id_prodhues = new SelectList(db.Prodhues, "Id_prodhues", "Emertim", shishe.id_prodhues);
            return View();
        }

        public ActionResult Delete(int id)
        {
            Shishe model = new Shishe();
            if (id > 0)
            {
                Shishe emp = db.Shishe.SingleOrDefault(x => x.Id_shishe == id);
                model.Id_shishe = emp.Id_shishe;
            }
            return PartialView("DeleteShishe", model);
        }

        // POST: Kategori/Delete/5
        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            Shishe sh = db.Shishe.Find(id);
            db.Shishe.Remove(sh);
            db.SaveChanges();
            return RedirectToAction("Index", "Prodhues");
        }

        [HttpPost]
        public JsonResult Update(ShisheModel shishe)
        {
            db.Configuration.ProxyCreationEnabled = false;
            Shishe sh = db.Shishe.Where(p => p.Id_shishe == shishe.Id).FirstOrDefault();
            sh.status = shishe.Status;
            db.SaveChanges();
            return Json(sh, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

ShisheVere/Views/Shishe/Create.cshtml
@model ShisheVere.Models.Shishe

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Shishe", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id_shishe)
    <div class="form-horizontal">
        <h4>Shishe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Emertim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Emertim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Emertim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kapacitet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kapacitet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kapacitet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pesha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pesha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pesha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gjatesia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gjatesia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gjatesia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Diametri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Diametri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diametri, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" multiple required/>
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.id_kategori, "Kategoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_kategori", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_kategori, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_prodhues, "Prodhuesi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_prodhues", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_prodhues, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShisheVere/Views/Shishe/Delete.cshtml
@model ShisheVere.Models.Shishe

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Shishe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KATEGORI.Emertim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KATEGORI.Emertim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prodhues.Emertim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prodhues.Emertim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Emertim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Emertim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kapacitet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kapacitet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pesha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pesha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gjatesia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gjatesia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Diametri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diametri)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShisheVere/Views/Shishe/Details.cshtml
@model ShisheVere.Models.Shishe

@{
    ViewBag.Title = "Details";
}

<h2>Detajet</h2>

<div>
 
        <table class="table">

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.KATEGORI.Emertim)
                </th>
                <td>
                    @Html.DisplayFor(model => model.KATEGORI.Emertim)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Prodhues.Emertim)
                </th>

                <td>
                    @Html.DisplayFor(model => model.Prodhues.Emertim)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Emertim)
                </th>

                <td>
                    @Html.DisplayFor(model => model.Emertim)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Kapacitet)
                </th>

                <td>
                    @Html.DisplayFor(model => model.Kapacitet)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Pesha)
                </th>

                <td>
                    @Html.DisplayFor(model => model.Pesha)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Gjatesia)
                </th>

                <td>
                    @Html.DisplayFor(model => model.Gjatesia)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Diametri)
                </th>

                <td>
                    @Html.DisplayFor(model => model.Diametri)
                </td>
            </tr>
        </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id_shishe, @class = "btn btn-success"  })  |
    @Html.ActionLink("Shikoni detajet per cdo shishe", "Index", new { @class = "btn btn-success"  })  |
    <a href="@Url.Action("AddToCart", "ShoppingCart", new { id = Model.Id_shishe,@class = "btn btn-success"  } )">Add to cart</a>
</p>

ShisheVere/Views/Shishe/Edit.cshtml
@model ShisheVere.Models.Shishe

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Shishe", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Shishe</h4>
        <hr />
        @if (TempData["edit"] != null)
        {
            <label style="color:maroon;"> @TempData["edit"] </label>
                <br /><br />
        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_shishe)

        <div class="form-group">
            @Html.LabelFor(model => model.Emertim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Emertim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Emertim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kapacitet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kapacitet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kapacitet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pesha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pesha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pesha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gjatesia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gjatesia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gjatesia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Diametri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Diametri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Diametri, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" multiple required />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Kategoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_kategori", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_kategori, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Prodhuesi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_prodhues", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_prodhues, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShisheVere/Views/Shishe/Index.cshtml
@model IEnumerable<ShisheVere.Models.Shishe>

@{
    ViewBag.Title = "Index";
}
<body onload="myFunction(),filter()">
    <h2>Detajet e shisheve
</h2>
    <br />
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <p>
        <label>Filter by gjatesi (cm) & by diameter (cm)</label> <br />
        <div class="form-container" style="display:inline-block;">         
            <label>Gjatesia :</label>
            <select id="gjatesi">
                <option>Zgjidh</option>
            </select>
        </div>
        &nbsp;&nbsp;
        <div class="class1" style="display:inline-block;">
            <label>Diametri :</label>
            <select id="diameter">
                <option>Zgjidh</option>
            </select>
        </div>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <label class="class1"></label>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <button onclick="filter()" class="btn btn-info btn-md"><span class="glyphicon glyphicon-filter"></span>Filter</button>
    </p>
    <table class="table" id="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KATEGORI.Emertim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prodhues.Emertim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Emertim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kapacitet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pesha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gjatesia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Diametri)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KATEGORI.Emertim)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prodhues.Emertim)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Emertim)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kapacitet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pesha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gjatesia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Diametri)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id_shishe }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id_shishe }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id_shishe })


                </td>
            </tr>
        }

    </table>
</body>
<script>
  function myFunction()
    {
        var table = document.getElementById("table");
        var tr = table.getElementsByTagName("tr");
        var arr = [];
        var arr1 = [];
        for (i = 1; i < tr.length; i++)
        {
            var txt = table.rows[i].cells.item(5).textContent.trim();

            if (txt == arr.find(function (el) { return el == txt; }))
                {

                }
            else
            {
                    arr.push(txt);
                    var x = document.getElementById("gjatesi");
                    var option = document.createElement("option");
                    option.text = txt;
                    x.add(option);
             }

            var txt1 = table.rows[i].cells.item(6).textContent.trim();
            if (txt1 == arr1.find(function (el) { return el == txt1; }))
            {

            }
            else
            {
                arr1.push(txt1);
                var x1 = document.getElementById("diameter");
                var option = document.createElement("option");
                option.text = txt1;
                x1.add(option);
            }
        }
    }


      function filter(){
          var lista1,lista2, filter1,filter2, table, tr, td, i;
          lista1 = document.getElementById("gjatesi");
          lista2 = document.getElementById("diameter");
          filter1 = lista1.options[lista1.selectedIndex].text;
          filter2 = lista2.options[lista2.selectedIndex].text;
          table = document.getElementById("table");
          tr = table.getElementsByTagName("tr");
         for (i = 1; i < tr.length; i++) {
              var txt = table.rows[i].cells.item(5).textContent.trim();
              var txt1 = table.rows[i].cells.item(6).textContent.trim();
              if (filter1 == "Zgjidh" && filter2 =="Zgjidh")
              {
                  for (i = 0; i < tr.length; i++)
                      tr[i].style.display = "";
              }
              else if (filter1 == "Zgjidh" && filter2 != "Zgjidh")
              {
                  if(txt1==filter2)
                      tr[i].style.display = "";
              }
              else if (filter1 != "Zgjidh" && filter2 == "Zgjidh")
              {
                  if (txt == filter1)
                      tr[i].style.display = "";
              }
              else if (txt == filter1 && txt1 == filter2)
              {
                  tr[i].style.display = "";
              }
              else
              {
                  tr[i].style.display = "none";
              }

          }
      }


</script>

ShisheVere/Views/Shishe/UserDetails.cshtml
@model ShisheVere.Models.Shishe

@{
    ViewBag.Title = "Details";
}

<h2>Detajet</h2>

<div>

    <table class="table">

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.KATEGORI.Emertim)
            </th>
            <td>
                @Html.DisplayFor(model => model.KATEGORI.Emertim)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Prodhues.Emertim)
            </th>

            <td>
                @Html.DisplayFor(model => model.Prodhues.Emertim)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Emertim)
            </th>

            <td>
                @Html.DisplayFor(model => model.Emertim)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Kapacitet)
            </th>

            <td>
                @Html.DisplayFor(model => model.Kapacitet)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pesha)
            </th>

            <td>
                @Html.DisplayFor(model => model.Pesha)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Gjatesia)
            </th>

            <td>
                @Html.DisplayFor(model => model.Gjatesia)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Diametri)
            </th>

            <td>
                @Html.DisplayFor(model => model.Diametri)
            </td>
        </tr>
    </table>
</div>
<p>

    @Html.ActionLink("Shikoni detajet per cdo shishe", "Index")  |
    <a href="@Url.Action("AddToCart", "ShoppingCart", new { id = Model.Id_shishe,@class="btn btn-success" })">Add to cart</a>
</p>